CREATE DATABASE DB_APIMADRID;
USE DB_APIMADRID;

CREATE TABLE IMAGES (
    Id CHAR(36) PRIMARY KEY,
    RelatedId CHAR(36),
    RelatedType VARCHAR(50),
    Url JSON,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESTAURANT (
    Id CHAR(36) PRIMARY KEY,
    Name VARCHAR(50),
    Email VARCHAR(50),
    Address VARCHAR(100)
);
