CREATE DATABASE DB_APIMADRID;
USE DB_APIMADRID;

CREATE TABLE IMAGES (
    id CHAR(36) PRIMARY KEY,
    relatedId CHAR(36),
    relatedType VARCHAR(50),
    url VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESTAURANT (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(50),
    address VARCHAR(100)
);

CREATE TABLE USERS (
    id VARCHAR(255) PRIMARY KEY,  -- ID proporcionado por Google OAuth
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE REFRESH_TOKENS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    token TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE LOCATION (
    id CHAR(36) PRIMARY KEY,
    relatedId CHAR(36),
    relatedType VARCHAR(50),
    address VARCHAR(500) NOT NULL,
    latitude VARCHAR(50),
    longitude VARCHAR(50),
    town VARCHAR(30),
    country VARCHAR(30),
    county VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
